status_choice = (
("Present", "Present"),
("Present Event", "Present Event"),
("Present Work", "Present Work"),
("AL", "AL"),
("OL", "OL"),
("OIL", "OIL"),
("RSO", "RSO"),
("RSI", "RSI"),
("MA", "MA"),
("MC", "MC"),
("OA", "OA"),
("AO", "AO"),
("CSE", "CSE"),
("OOC", "OOC"),
)

rank_choice = (
("REC", "REC"),
("PTE", "PTE"),
("LCP", "LCP"),
("CPL", "CPL"),
("CFC", "CFC"),
("3SG", "3SG"),
("2SG", "2SG"),
("1SG", "1SG"),
("SSG", "SSG"),
("MSG", "MSG"),
("3WO", "3WO"),
("2WO", "2WO"),
("1WO", "1WO"),
("MAJ", "MAJ"),
("DX06", "DX06"),
("DX07", "DX07"),
("DX10", "DX10"),
)