# Generated by Django 3.0.4 on 2020-03-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='rank_nric_name',
            new_name='nric',
        ),
    ]
