# Generated by Django 3.0.4 on 2020-03-20 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200320_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('present', 'present'), ('leave', 'leave')], default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 17, 23, 8, 433928)),
        ),
    ]
