# Generated by Django 3.0.4 on 2020-03-20 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200320_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 17, 46, 20, 420687)),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('present', 'present'), ('leave', 'leave'), ('MC', 'MC')], default='present', max_length=30),
        ),
    ]
