# Generated by Django 3.0.4 on 2020-03-20 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200320_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 18, 7, 55, 331551)),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Leave', 'Leave'), ('MC', 'MC')], default='present', max_length=30),
        ),
    ]
