# Generated by Django 3.0.4 on 2020-03-21 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200320_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 13, 7, 53, 402298)),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(1, 'Present'), (2, 'Present Event'), (3, 'Present Work'), (4, 'AL'), (5, 'OL'), (6, 'OIL'), (7, 'RSO'), (8, 'RSI'), (9, 'MA'), (10, 'MC'), (11, 'OA'), (12, 'AO'), (13, 'CSE'), (14, 'OOC')]),
        ),
    ]
