# Generated by Django 3.0.4 on 2020-03-21 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200321_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 13, 16, 10, 191354)),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Present Event', 'Present Event'), ('Present Work', 'Present Work'), ('AL', 'AL'), ('OL', 'OL'), ('OIL', 'OIL'), ('RSO', 'RSO'), ('RSI', 'RSI'), ('MA', 'MA'), ('MC', 'MC'), ('OA', 'OA'), ('AO', 'AO'), ('CSE', 'CSE'), ('OOC', 'OOC')], default='present', max_length=30),
        ),
    ]
