# Generated by Django 3.0.4 on 2020-04-20 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200322_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 9, 5, 45, 668674, tzinfo=utc)),
        ),
    ]
