# Generated by Django 3.0.4 on 2020-04-20 09:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200420_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 9, 18, 17, 548475, tzinfo=utc)),
        ),
    ]
